### ISSUE TITLE
Make shell snippets in README more easily copyable

### ISSUE THREAD

**Issue by zyzzyxdonta** [psteinb/sota_on_uncertainties#1]
Code blocks in the README file have copy buttons. These copy actions also copy the `$` signs. The unattentive reader might click the copy button, paste into the terminal and get `-bash: $: command not found`. The code can be copied more easily if the `$` signs are removed. Instead, indication that the code is bash/shell should be given by adding the correct language to the code block.

E.g. instead of

````markdown
```
$ pip install something
```
````

this can be used:

````markdown
```bash
pip install something
```
````

For code blocks which also show the output, I think you could split them into two blocks: One with the code, one with the output. Though I'm not sure if this would be a great solution.

**Comment by psteinb** [comment]
Thanks for reporting. 
I fixed that with [07eaa9f](https://github.com/psteinb/sota_on_uncertainties/commit/07eaa9fb5b72c62f11cdd43e3b8a842afe7a892c) and [ddd513b](https://github.com/psteinb/sota_on_uncertainties/commit/ddd513b2aea18b7ad5bf031e8ec15ef924a2a401)
