### ISSUE TITLE
pip call missing command

### ISSUE THREAD

**Issue by zyzzyxdonta** [psteinb/sota_on_uncertainties#2]
Instead of

```bash
python -m pip torch...
```

this should be

```bash
python -m pip install torch...
```

https://github.com/psteinb/sota_on_uncertainties/blob/e5c9fc7288fbdf011a099b5bfeba82a76f256b98/README.md?plain=1#L67

**Comment by psteinb** [comment]
fixed with [af2bc77](https://github.com/psteinb/sota_on_uncertainties/commit/af2bc774f18df23a1f3ce060613b22243009adb1)
Thanks!
