### ISSUE TITLE
Error in jusuf Slurm config

### ISSUE THREAD

**Issue by zyzzyxdonta** [psteinb/sota_on_uncertainties#4]
I couldn't try it because I don't have access to Jusuf. But I'm fairly certain that there is an error in it. You specified the CPUs per task twice: Once with `-c`, once with `--cpus-per-task`.

https://github.com/psteinb/sota_on_uncertainties/blob/ddd513b2aea18b7ad5bf031e8ec15ef924a2a401/config/slurm/jusuf/config.yaml#L2

Also, the `ngpu` setting is not used in the cluster string.

**Comment by psteinb** [comment]
thanks for spotting this. slurm didn't throw an error.
Fixed with [84f9668](https://github.com/psteinb/sota_on_uncertainties/commit/84f9668e858fd45fd96f077ac8f6b9beb4966302)
